export type Store = {
  id: string;
  name: string;
  provinceId: string;
  province: string;
  city: string;
  barangay: string;
  contactName: string;
  contactNumber: string;
};

export const STORES: Store[] = [
  {
    id: "store_kapitolyo",
    name: "Kapitolyo",
    provinceId: "province_pasig",
    province: "Metro Manila",
    city: "Pasig City",
    barangay: "Kapitolyo",
    contactName: "Mia",
    contactNumber: "0917 000 0003",
  },
  {
    id: "store_guadalupe",
    name: "Guadalupe",
    provinceId: "province_makati",
    province: "Metro Manila",
    city: "Makati City",
    barangay: "Guadalupe Nuevo",
    contactName: "Rico",
    contactNumber: "0917 000 0002",
  },
  {
    id: "store_pasig_market",
    name: "Pasig Public Market",
    provinceId: "province_pasig",
    province: "Metro Manila",
    city: "Pasig City",
    barangay: "Market Area",
    contactName: "Ana",
    contactNumber: "0917 000 0004",
  },
  {
    id: "store_cainta_junction",
    name: "Cainta Junction",
    provinceId: "province_pasig",
    province: "Rizal",
    city: "Cainta",
    barangay: "Junction",
    contactName: "Leo",
    contactNumber: "0917 000 0005",
  },
  {
    id: "store_tiendesitas",
    name: "Tiendesitas",
    provinceId: "province_pasig",
    province: "Metro Manila",
    city: "Pasig City",
    barangay: "Ortigas Ave.",
    contactName: "Sara",
    contactNumber: "0917 000 0006",
  },
  {
    id: "store_poblacion",
    name: "Poblacion Main",
    provinceId: "province_makati",
    province: "Metro Manila",
    city: "Makati City",
    barangay: "Poblacion",
    contactName: "Jon",
    contactNumber: "0917 000 0007",
  },
  {
    id: "store_legazpi_village",
    name: "Legazpi Village",
    provinceId: "province_makati",
    province: "Metro Manila",
    city: "Makati City",
    barangay: "Legazpi Village",
    contactName: "Clara",
    contactNumber: "0917 000 0008",
  },
  {
    id: "store_salcedo",
    name: "Salcedo Park",
    provinceId: "province_makati",
    province: "Metro Manila",
    city: "Makati City",
    barangay: "Salcedo Village",
    contactName: "Luis",
    contactNumber: "0917 000 0009",
  },
  {
    id: "store_quirino_centro",
    name: "Quirino Centro",
    provinceId: "province_quirino",
    province: "Quirino",
    city: "Quirino",
    barangay: "Poblacion",
    contactName: "Marco",
    contactNumber: "0917 000 0010",
  },
  {
    id: "store_quirino_public_market",
    name: "Quirino Public Market",
    provinceId: "province_quirino",
    province: "Quirino",
    city: "Quirino",
    barangay: "Market Area",
    contactName: "Nina",
    contactNumber: "0917 000 0011",
  },
  {
    id: "store_maddela_town_center",
    name: "Maddela Town Center",
    provinceId: "province_maddela",
    province: "Quirino",
    city: "Maddela",
    barangay: "Town Center",
    contactName: "Oscar",
    contactNumber: "0917 000 0012",
  },
  {
    id: "store_maddela_market",
    name: "Maddela Public Market",
    provinceId: "province_maddela",
    province: "Quirino",
    city: "Maddela",
    barangay: "Public Market",
    contactName: "Paula",
    contactNumber: "0917 000 0013",
  },
  {
    id: "store_baler_bay",
    name: "Baler Bayfront",
    provinceId: "province_baler",
    province: "Aurora",
    city: "Baler",
    barangay: "Bay Area",
    contactName: "Rey",
    contactNumber: "0917 000 0014",
  },
  {
    id: "store_baler_market",
    name: "Baler Public Market",
    provinceId: "province_baler",
    province: "Aurora",
    city: "Baler",
    barangay: "Public Market",
    contactName: "Tina",
    contactNumber: "0917 000 0015",
  },
  {
    id: "store_dipaculao_beach",
    name: "Dipaculao Beachfront",
    provinceId: "province_dipaculao",
    province: "Aurora",
    city: "Dipaculao",
    barangay: "Beachfront",
    contactName: "Uma",
    contactNumber: "0917 000 0016",
  },
  {
    id: "store_dipaculao_market",
    name: "Dipaculao Public Market",
    provinceId: "province_dipaculao",
    province: "Aurora",
    city: "Dipaculao",
    barangay: "Public Market",
    contactName: "Vince",
    contactNumber: "0917 000 0017",
  },
];
